### ISSUE TITLE
Hand-write templates and check for subgraph isomorphism 

### ISSUE THREAD

**Issue by avanhatt** [avanhatt/dfg-coverings#6]

**Comment by avanhatt** [comment]
- [ ] Check if a hand-written template is matched at all
- [ ] Find all matches of a single template (multiple subgraph matches)
- [ ] Pass match mappings back to the LLVM pass
- [ ] Find all matches of multiple templates

**Comment by gyauney** [comment]
Finished by 5a2a543caaae47b0dfb3503c1d20adfb2ba88c8f.
