### ISSUE TITLE
Generate subgraph stencils

### ISSUE THREAD

**Issue by gyauney** [avanhatt/dfg-coverings#9]
- [x] exhaustively search for all 2-node subgraphs that appear in the graph
- [x] extend to 3-, ..., k-node subgraphs
- [x] merge best parts of both approaches

**Comment by orichardson** [comment]
New d

- [ ] search for collections of subgraphs with high coverage

**Comment by gyauney** [comment]
Merged into master in ed5dfe9624b6d302ac38233aab75d96a92a8a2bd.
